name: xcube-cci
channels:
  - conda-forge
dependencies:
  # Python
  - python >=3.10
  # Required
  - aiohttp >= 3.6
  - lxml >= 4.5
  - numpy >= 2.0
  - pydap >= 3.4,<=3.5.3
  - rioxarray
  - xarray >= 2025.4.0
  - xcube >= 1.8.0
  - xvec
  - zarr <3  # until we can ensure zarr 3 compatibility
  # Test libs
  - pytest
  - pytest-cov
